const pages=[...document.querySelectorAll('.page')],nav=[...document.querySelectorAll('nav button')];let completed=JSON.parse(localStorage.getItem('dkCompleted')||'[]'),xp=Number(localStorage.getItem('dkxp')||120),quotes=['Every great player starts with one brave practice.','Be curious like a scientist and persistent like a champion.','Small steps today build big skills tomorrow.','Mistakes are clues that help your brain level up.','Read the evidence, make your play, and keep learning.','A strong team listens, learns, and tries again.','Your next great idea could be hiding in the next paragraph.'];
// Educational content must use fictional/neutral names only. Personal names are never rendered in lessons, questions, choices, or examples.
function sanitizeLearningContent(){const raw=JSON.stringify(CHAPTERS);const clean=raw.replace(/Shreyas/gi,'Alex').replace(/Nagesh/gi,'Jordan');return JSON.parse(clean)}
const LEARNING_CHAPTERS=sanitizeLearningContent();
function showPage(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));nav.forEach(b=>b.classList.toggle('active',b.dataset.page===id));if(id==='library')renderLibrary('all');if(id==='learn')renderPath();if(id==='quiz')renderQuizChapters();if(id==='progress')renderProgress();location.hash=id;window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)showPage(b.dataset.page)});
function addXP(n){xp+=n;localStorage.setItem('dkxp',xp);syncStats()}function syncStats(){document.querySelector('#xp')&&(document.querySelector('#xp').textContent=xp);document.querySelector('#parentXP')&&(document.querySelector('#parentXP').textContent=xp);document.querySelector('#chaptersDone')&&(document.querySelector('#chaptersDone').textContent=completed.length);document.querySelector('#parentLessons')&&(document.querySelector('#parentLessons').textContent=completed.length)}
function saveComplete(id){if(!completed.includes(id)){completed.push(id);localStorage.setItem('dkCompleted',JSON.stringify(completed));addXP(10)}}
function renderLibrary(grade){const el=document.getElementById('chapterGrid');if(!el)return;el.innerHTML=LEARNING_CHAPTERS.filter(c=>grade==='all'||c.grade===grade).map((c)=>`<article class="chapter-card"><div class="chapter-icon">${c.icon}</div><div><span class="tag">GRADE ${c.grade} • ${c.unit}</span><h3>Chapter ${LEARNING_CHAPTERS.indexOf(c)+1}: ${c.title}</h3><p>${c.skills.join(' • ')}</p><small>${c.lessons.length} guided lessons</small></div><button class="primary" data-chapter="${c.id}">Open →</button></article>`).join('')}
function renderPath(){const el=document.getElementById('pathGrid');if(el)el.innerHTML=LEARNING_CHAPTERS.map((c,i)=>`<article class="chapter-card"><div class="chapter-icon">${c.icon}</div><div><span class="tag">${c.grade==='4'?'FOUNDATION':'STRETCH'}</span><h3>${i+1}. ${c.title}</h3><p>${c.unit} • ${c.skills.join(' • ')}</p></div><button class="primary" data-chapter="${c.id}">Open</button></article>`).join('')}
function renderQuizChapters(){const el=document.getElementById('quizChapters');if(el)el.innerHTML=LEARNING_CHAPTERS.map(c=>`<article class="chapter-card"><div class="chapter-icon">${c.icon}</div><div><span class="tag">${c.unit}</span><h3>${c.title}</h3><p>3-question chapter challenge</p></div><button class="primary" data-chapter="${c.id}">Quiz →</button></article>`).join('')}
function openChapter(id){const c=LEARNING_CHAPTERS.find(x=>x.id===id);if(!c)return;document.getElementById('chapterReader').innerHTML=`<div class="pagehead"><button class="back" data-page="library">← Library</button><span class="eyebrow">CHAPTER ${LEARNING_CHAPTERS.indexOf(c)+1} • GRADE ${c.grade}</span><h1>${c.icon} ${c.title}</h1><p>${c.unit} • ${c.skills.join(' • ')}</p></div><div class="lesson-list">${c.lessons.map((l,i)=>`<article class="lesson-panel"><div class="lesson-number">LESSON ${i+1}</div><h2>${l.title}</h2><span class="tag">${l.type}</span><div class="lesson-text">${l.text}</div><h3>${l.question}</h3>${l.choices.map((x,j)=>`<button class="answer lessonAnswer" data-chapter="${c.id}" data-lesson="${i}" data-choice="${j}">${x}</button>`).join('')}<div class="feedback" id="feedback-${c.id}-${i}"></div></article>`).join('')}</div>`;showPage('chapter')}
document.addEventListener('click',e=>{const c=e.target.closest('[data-chapter]');if(c&&!e.target.closest('.lessonAnswer'))openChapter(c.dataset.chapter);const a=e.target.closest('.lessonAnswer');if(a){const c=LEARNING_CHAPTERS.find(x=>x.id===a.dataset.chapter),l=c.lessons[Number(a.dataset.lesson)],ok=Number(a.dataset.choice)===l.answer,fb=document.getElementById(`feedback-${c.id}-${a.dataset.lesson}`);a.parentElement.querySelectorAll('.lessonAnswer').forEach(x=>x.disabled=true);a.classList.add(ok?'correct':'wrong');fb.textContent=ok?'Excellent! +10 XP. You used the skill correctly.':'Not quite. Re-read the lesson and think about the clue.';if(ok)saveComplete(`${c.id}-${a.dataset.lesson}`)}});
document.addEventListener('click',e=>{const f=e.target.closest('.filter');if(f){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');renderLibrary(f.dataset.grade)}});
function renderProgress(){const el=document.getElementById('progressCards');if(!el)return;const units={};LEARNING_CHAPTERS.forEach(c=>{units[c.unit]??={done:0,total:0};units[c.unit].total+=c.lessons.length;c.lessons.forEach((_,i)=>{if(completed.includes(`${c.id}-${i}`))units[c.unit].done++})});el.innerHTML=Object.entries(units).map(([u,v])=>{const p=Math.round(v.done/v.total*100);return `<article class="card"><h3>${u}</h3><div class="bar"><i style="width:${p}%"></i></div><b>${p}%</b><p>${v.done}/${v.total} lessons</p></article>`}).join('')}
document.getElementById('saveDraft')?.addEventListener('click',()=>{localStorage.setItem('dkplan',document.getElementById('plan').value);localStorage.setItem('dkdraft',document.getElementById('draft').value);addXP(10);document.getElementById('draftMsg').textContent='Draft saved! +10 XP'});if(document.getElementById('plan'))document.getElementById('plan').value=localStorage.getItem('dkplan')||'';if(document.getElementById('draft'))document.getElementById('draft').value=localStorage.getItem('dkdraft')||'';if(document.getElementById('dailyQuote'))document.getElementById('dailyQuote').textContent='“'+quotes[new Date().getDate()%quotes.length]+'”';if(document.getElementById('libraryCount'))document.getElementById('libraryCount').textContent=LEARNING_CHAPTERS.length;syncStats();showPage(pages.some(p=>p.id===location.hash.slice(1))?location.hash.slice(1):'dashboard');