const CHAPTERS = [
  {id:'c1',grade:'4',unit:'Reading Foundations',title:'The Rookie Reader',icon:'📖',skills:['Main idea','Key details','Summarizing'],lessons:[
    {title:'Find the Big Idea',type:'Reading',text:'Coach Rafi noticed that Shreyas could remember exciting details but sometimes missed what a passage was mostly about. He taught him to ask, “What is the author mostly trying to tell me?” Shreyas practiced by circling repeated ideas and crossing out details that did not support them. Soon, he could explain a passage in one clear sentence.',question:'What is the main idea?',choices:['Readers can find the main idea by noticing repeated ideas and important details.','Every detail in a passage is equally important.','Shreyas only learned about soccer.'],answer:0},
    {title:'Evidence Huddle',type:'Reading',text:'During a dinosaur dig, the team found three small footprints beside a riverbank. No one immediately announced which dinosaur made them. Instead, the scientists measured the tracks, photographed them, and compared them with known fossils. Their notes helped the team make a careful conclusion.',question:'Which detail best shows that the scientists used evidence?',choices:['They made a quick guess.','They measured, photographed, and compared the footprints.','They left the riverbank.'],answer:1},
    {title:'One-Sentence Summary',type:'Practice',text:'A strong summary names the most important idea and leaves out minor details. It should be short enough to remember and accurate enough to explain the passage.',question:'Which is the best summary of the lesson?',choices:['A summary includes every detail.','A summary gives the important idea in a concise way.','A summary should always be one word.'],answer:1}
  ]},
  {id:'c2',grade:'4',unit:'Reading Detective',title:'Dinosaur Detectives',icon:'🦖',skills:['Inference','Text evidence','Cause and effect'],lessons:[
    {title:'Read Between the Tracks',type:'Reading',text:'The field was empty when Maya arrived, but the soccer ball was still resting near the goal. Wet footprints crossed the grass toward the equipment shed. Maya grabbed her notebook and followed them. Inside the shed, she found the missing practice cones stacked neatly beside a raincoat.',question:'What can you infer?',choices:['Someone moved the cones after the rain started.','The cones disappeared forever.','Maya was playing a game alone.'],answer:0},
    {title:'Because of the Storm',type:'Cause & Effect',text:'A sudden storm rolled across the soccer field. The players moved practice indoors, where they worked on passing drills. Because the rain continued, the coach postponed the scrimmage until the next day.',question:'What was the effect of the storm?',choices:['The team practiced indoors and postponed the scrimmage.','The team went swimming.','The coach canceled soccer forever.'],answer:0},
    {title:'Prove It',type:'Evidence',text:'Good readers support an inference with a clue from the text. Think: “I infer ___ because the text says ___.” This turns a guess into evidence-based thinking.',question:'Which sentence uses evidence?',choices:['I think the character is nervous because she keeps checking the clock.','The character is nervous because I say so.','The clock is interesting.'],answer:0}
  ]},
  {id:'c3',grade:'4',unit:'Text Structure',title:'How Authors Build Ideas',icon:'🧩',skills:['Sequence','Compare/contrast','Problem/solution'],lessons:[
    {title:'First, Next, Finally',type:'Reading',text:'First, the paleontologists mapped the dig site. Next, they carefully removed layers of soil. Finally, they labeled each fossil and placed it in a protective case. Following the sequence helped the team avoid damaging important evidence.',question:'Which structure organizes the passage?',choices:['Sequence of events','Compare and contrast','Problem and solution'],answer:0},
    {title:'Two Strikers',type:'Compare',text:'T. rex and a soccer striker both had powerful ways to move through their environments. A T. rex used strong legs and a long tail for balance, while a striker uses footwork and quick changes of direction. Both depend on balance to move effectively.',question:'What do the two subjects have in common?',choices:['Both depend on balance.','Both play soccer.','Both have long tails.'],answer:0},
    {title:'Fix the Fossil Problem',type:'Problem/Solution',text:'A museum had many fossils but visitors found the displays confusing. The staff grouped fossils by time period, added simple labels, and created a walking path. Visitors could now understand how dinosaurs changed over time.',question:'What was the solution?',choices:['The museum closed.','The staff reorganized displays and added clear labels.','Visitors stopped asking questions.'],answer:1}
  ]},
  {id:'c4',grade:'4',unit:'Vocabulary',title:'Word Power Camp',icon:'🔤',skills:['Context clues','Prefixes','Suffixes'],lessons:[
    {title:'Context Clue Kickoff',type:'Vocabulary',text:'The trail was treacherous, with loose rocks and steep drops. The hikers moved slowly and watched every step.',question:'What does treacherous most likely mean?',choices:['Safe and easy','Dangerous or risky','Very short'],answer:1},
    {title:'Prefix Power',type:'Word Parts',text:'The prefix re- often means “again.” Rewrite means write again. Rebuild means build again. Reread means read again.',question:'What does replay mean?',choices:['Play before','Play again','Play badly'],answer:1},
    {title:'Suffix Squad',type:'Word Parts',text:'The suffix -ful can mean “full of.” A helpful person is full of help; a playful puppy is full of play.',question:'What does hopeful suggest?',choices:['Full of hope','Without hope','Against hope'],answer:0}
  ]},
  {id:'c5',grade:'4',unit:'Grammar',title:'Sentence Stadium',icon:'🏟️',skills:['Complete sentences','Fragments','Run-ons'],lessons:[
    {title:'Complete the Play',type:'Grammar',text:'A complete sentence expresses a complete thought. It usually contains a subject and a predicate. Fragment: “After the game.” Complete: “We celebrated after the game.”',question:'Which is a complete sentence?',choices:['After the dinosaur escaped.','The team celebrated after the game.','Running toward the goal.'],answer:1},
    {title:'Stop the Run-On',type:'Grammar',text:'A run-on sentence joins two complete thoughts incorrectly. You can fix it with a period, semicolon, or conjunction.',question:'Which fixes the run-on “The ball rolled away I chased it.”?',choices:['The ball rolled away, so I chased it.','The ball rolled away I chased it.','The ball rolled away chased it.'],answer:0},
    {title:'Sentence Variety',type:'Grammar',text:'Strong writers vary sentence beginnings and lengths. This makes writing smoother and more interesting to read.',question:'Why vary sentence structure?',choices:['To make every sentence identical','To make writing smoother and more interesting','To remove all verbs'],answer:1}
  ]},
  {id:'c6',grade:'4',unit:'Grammar',title:'Parts-of-Speech League',icon:'⚽',skills:['Nouns','Verbs','Adjectives','Adverbs'],lessons:[
    {title:'Noun Navigator',type:'Grammar',text:'A noun names a person, place, thing, or idea. Dinosaur, stadium, Shreyas, and courage are all nouns.',question:'Which word is a noun?',choices:['quickly','stadium','run'],answer:1},
    {title:'Verb Velocity',type:'Grammar',text:'A verb shows an action or state of being. Sprint, studied, imagined, and is are verbs.',question:'Which word is a verb?',choices:['imagined','fossil','bright'],answer:0},
    {title:'Describe the Play',type:'Grammar',text:'Adjectives describe nouns. Adverbs often describe verbs and tell how, when, or where an action happens.',question:'Which word is an adjective in “The enormous dinosaur roared loudly”?',choices:['enormous','roared','loudly'],answer:0}
  ]},
  {id:'c7',grade:'4',unit:'Writing',title:'Story Builder Academy',icon:'✍️',skills:['Narrative structure','Details','Dialogue'],lessons:[
    {title:'Build a Plot',type:'Writing',text:'A narrative usually has a beginning that introduces characters and setting, a middle where a problem develops, and an ending that resolves the problem.',question:'Where does the main problem usually develop?',choices:['Only in the title','In the middle of the story','After the story ends'],answer:1},
    {title:'Add Sensory Details',type:'Writing',text:'Instead of writing “The stadium was exciting,” a writer might say, “The crowd thundered as the lights flashed across the field.” Specific details help readers imagine the scene.',question:'Which sentence uses sensory detail?',choices:['The stadium was exciting.','The crowd thundered as the lights flashed.','It was a place.'],answer:1},
    {title:'Dialogue That Works',type:'Writing',text:'Dialogue should sound like something a character would actually say. It can reveal feelings, move the plot, and show relationships.',question:'What can dialogue do?',choices:['Reveal character and move the story','Replace every paragraph','Remove the plot'],answer:0}
  ]},
  {id:'c8',grade:'4',unit:'Writing',title:'Opinion Championship',icon:'🏆',skills:['Claim','Reasons','Evidence'],lessons:[
    {title:'Make a Claim',type:'Writing',text:'An opinion paragraph begins with a clear claim. The claim tells the reader what you believe or recommend.',question:'Which is the clearest claim?',choices:['Dinosaurs are things.','I believe every school should have a reading club because it helps students discover books.','Books exist.'],answer:1},
    {title:'Strong Reasons',type:'Writing',text:'A reason explains why a claim makes sense. Strong reasons are specific and connected to the claim.',question:'Which is a strong reason for a reading club?',choices:['It is good.','Students can practice reading and share recommendations.','I like it.'],answer:1},
    {title:'Evidence Boost',type:'Writing',text:'Evidence supports a reason with facts, examples, or information from a source or experience.',question:'What strengthens an opinion?',choices:['Evidence and examples','Repeating the claim five times','A random detail'],answer:0}
  ]},
  {id:'c9',grade:'5',unit:'Reading',title:'Theme Hunters',icon:'🌟',skills:['Theme','Character change','Lessons'],lessons:[
    {title:'Theme Is a Lesson',type:'Reading',text:'A theme is a message about life, not simply one word. “Courage” is a topic; “Courage grows when we face challenges” is a theme.',question:'Which is a theme?',choices:['Friendship','Courage grows when we face challenges.','A brave knight'],answer:1},
    {title:'Watch the Character Change',type:'Reading',text:'At first, Leo avoided speaking during team meetings. After a teammate thanked him for a useful idea, Leo began sharing one thought each meeting. By the final game, he confidently helped plan the strategy.',question:'How did Leo change?',choices:['He became more willing to share ideas.','He stopped playing.','He forgot the strategy.'],answer:0},
    {title:'Theme Evidence',type:'Reading',text:'To identify theme, notice what a character learns, how a problem is solved, and which ideas repeat. Then support your answer with details.',question:'Which evidence best supports a theme about persistence?',choices:['The character quits immediately.','The character tries several strategies before succeeding.','The character changes the subject.'],answer:1}
  ]},
  {id:'c10',grade:'5',unit:'Vocabulary',title:'Word Roots Expedition',icon:'🧭',skills:['Greek/Latin roots','Multiple meaning','Precise words'],lessons:[
    {title:'Root: bio',type:'Vocabulary',text:'The Greek root bio means “life.” Biology is the study of life, and biography is a written account of a person’s life.',question:'What would bioluminescent most likely relate to?',choices:['Living things producing light','Ancient rocks only','Soccer rules'],answer:0},
    {title:'Multiple Meanings',type:'Vocabulary',text:'A word can have more than one meaning. In “The bat flew from the cave,” bat means an animal. In “She swung the bat,” it means sports equipment.',question:'Which meaning fits “The player swung the bat”?',choices:['A flying mammal','Sports equipment','A cave'],answer:1},
    {title:'Choose the Precise Word',type:'Vocabulary',text:'Precise words make writing stronger. Instead of “walked,” a writer might choose marched, shuffled, wandered, or sprinted depending on the action.',question:'Which word best fits “He moved quickly toward the goal”?',choices:['sprinted','wandered','strolled'],answer:0}
  ]},
  {id:'c11',grade:'5',unit:'Grammar',title:'Punctuation Playbook',icon:'📝',skills:['Commas','Quotation marks','Apostrophes'],lessons:[
    {title:'Comma Pass',type:'Grammar',text:'Commas can separate items in a series: “We packed fossils, notebooks, brushes, and water.” They can also follow introductory phrases.',question:'Which sentence uses commas correctly?',choices:['We packed fossils notebooks brushes and water.','We packed fossils, notebooks, brushes, and water.','We packed, fossils notebooks brushes and water.'],answer:1},
    {title:'Quote the Coach',type:'Grammar',text:'Quotation marks show a speaker’s exact words. “Keep your eyes on the ball,” Coach Rafi said.',question:'Which punctuation marks show exact spoken words?',choices:['Parentheses','Quotation marks','Hyphens'],answer:1},
    {title:'Apostrophe Attack',type:'Grammar',text:'Apostrophes can show possession or contractions. “The player’s cleats” shows possession. “Don’t” is a contraction for “do not.”',question:'What does the apostrophe show in “Shreyas’s notebook”?',choices:['Possession','A question','A plural word'],answer:0}
  ]},
  {id:'c12',grade:'5',unit:'Informative Writing',title:'Explain It Like a Pro',icon:'🔬',skills:['Topic sentence','Facts','Organization'],lessons:[
    {title:'Topic Sentence',type:'Writing',text:'An informative paragraph begins with a topic sentence that introduces the subject and focus. The rest of the paragraph develops that idea.',question:'Which is a strong topic sentence?',choices:['Dinosaurs were interesting.','Fossil evidence helps scientists learn how prehistoric animals lived.','I saw a fossil once.'],answer:1},
    {title:'Fact or Opinion?',type:'Writing',text:'A fact can be checked with evidence. An opinion expresses a belief or judgment.',question:'Which is a fact?',choices:['T. rex is the coolest dinosaur.','Fossils can preserve evidence of ancient life.','Everyone should love dinosaurs.'],answer:1},
    {title:'Organize the Explanation',type:'Writing',text:'Informative writing often uses an introduction, logically grouped information, transitions, and a conclusion that reminds readers of the main idea.',question:'What helps readers follow ideas?',choices:['Random order','Logical organization and transitions','No topic sentence'],answer:1}
  ]},
  {id:'c13',grade:'5',unit:'Poetry',title:'Poetry Pitch',icon:'🎤',skills:['Imagery','Figurative language','Sound'],lessons:[
    {title:'Paint With Words',type:'Poetry',text:'Poets use imagery to help readers see, hear, smell, taste, or feel a scene. “Silver rain tapped the window” creates a sound and visual image.',question:'What does imagery help readers do?',choices:['Imagine a scene using the senses','Forget the setting','Count sentences'],answer:0},
    {title:'Simile Sprint',type:'Poetry',text:'A simile compares two things using like or as. “The striker was as quick as a cheetah” compares speed.',question:'Which is a simile?',choices:['The ball was lightning.','The ball moved like lightning.','The ball moved.'],answer:1},
    {title:'Sound Matters',type:'Poetry',text:'Poets can use rhyme, rhythm, repetition, and alliteration to create musical effects.',question:'What can repetition do?',choices:['Create emphasis and rhythm','Remove meaning','Make every poem factual'],answer:0}
  ]},
  {id:'c14',grade:'5',unit:'Research',title:'Fact-Finding Lab',icon:'🔎',skills:['Sources','Notes','Paraphrasing'],lessons:[
    {title:'Source Smarts',type:'Research',text:'A trustworthy source gives clear information and allows readers to check where the information came from. Good researchers compare sources instead of trusting the first result.',question:'What should a careful researcher do?',choices:['Use the first result without checking.','Compare trustworthy sources.','Copy everything.'],answer:1},
    {title:'Smart Notes',type:'Research',text:'Good notes capture key ideas in your own words. Recording the source beside each note makes it easier to give credit later.',question:'Why take notes in your own words?',choices:['To understand and remember ideas','To copy faster','To hide the source'],answer:0},
    {title:'Paraphrase Practice',type:'Research',text:'Paraphrasing means restating information in your own words while keeping the original meaning. It is different from copying a few words and changing the order.',question:'A good paraphrase should...',choices:['Keep the meaning but use your own wording.','Copy the sentence exactly.','Change the facts.'],answer:0}
  ]},
  {id:'c15',grade:'5',unit:'Integrated ELA',title:'DinoKick Championship',icon:'🥇',skills:['Reading','Vocabulary','Grammar','Writing'],lessons:[
    {title:'Captain’s Challenge',type:'Mixed',text:'The final match was tied. Instead of blaming one another, the players listened, adjusted their strategy, and encouraged the newest teammate. With seconds left, the team scored. Their coach reminded them that strong teams improve by learning together.',question:'Which theme best fits the passage?',choices:['Teamwork and learning from challenges lead to growth.','Winning is all that matters.','New teammates should stay quiet.'],answer:0},
    {title:'Precision Play',type:'Mixed',text:'The captain carefully studied the field before choosing a new position. The word carefully tells how the captain studied.',question:'What part of speech is carefully?',choices:['Noun','Adverb','Adjective'],answer:1},
    {title:'Final Writing Mission',type:'Writing',text:'Write a paragraph explaining one lesson you can learn from teamwork. State your idea, give two specific examples, and finish with a concluding sentence.',question:'What should your paragraph include?',choices:['A claim or idea, supporting examples, and a conclusion.','Only a title.','A list of unrelated words.'],answer:0}
  ]}
];
