const DAILY_ROTATION=[
{quote:'Every new word is a fossil from a story waiting to be discovered.',mission:'Find one clue that proves your answer.',title:'Fossil Footprints',question:'Why does measuring tracks help a paleontologist?',choices:['It provides evidence.','It makes fossils disappear.','It proves every dinosaur moved the same way.'],answer:0},
{quote:'Keep practicing—great plays and great ideas both take teamwork.',mission:'Unlock one new word and use it in a sentence.',title:'The Final Pass',question:'Which trait is best shown when players communicate and wait for an open teammate?',choices:['Carelessness','Teamwork and patience','Giving up'],answer:1},
{quote:'Curiosity is your secret superpower: ask one more question today.',mission:'Circle a word whose meaning you can infer from context.',title:'The Mystery Word',question:'The cave was enormous. What does enormous most likely mean?',choices:['Very large','Very quiet','Very old'],answer:0},
{quote:'A tricky paragraph is just a puzzle waiting for a clever reader.',mission:'Find the main idea of a short passage.',title:'Grammar Goal',question:'Which edit correctly adds a comma after an introductory phrase?',choices:['After the game, the players packed their bags.','After, the game the players packed their bags.','After the game the, players packed their bags.'],answer:0},
{quote:'Missed a question? Dig for the clue, learn, and make your next play.',mission:'Use evidence to support one answer.',title:'Evidence Assist',question:'A character tries several strategies and learns from each attempt. Which theme fits?',choices:['Persistence can help solve difficult problems.','Problems should always be ignored.','The first attempt is always perfect.'],answer:0},
{quote:'Small steps build big skills, just like a team builds a winning play.',mission:'Spot a prefix, suffix, or root.',title:'Dino Dialogue',question:'What does a teammate suggesting that dinosaurs explore together reveal?',choices:['A plan based on teamwork','A dislike of exploration','A need to stop reading'],answer:0},
{quote:'Your ideas can score big when you support them with strong evidence.',mission:'Write three vivid sentences about a soccer play.',title:'Strong Writer',question:'Why is “The ball curled into the upper corner of the net” stronger than “The goal was good”?',choices:['It adds a specific, vivid detail.','It removes the action.','It makes the sentence less clear.'],answer:0}
];
const i=Math.floor(Date.now()/86400000)%DAILY_ROTATION.length,today=DAILY_ROTATION[i];
const q=document.getElementById('dailyQuote');if(q)q.textContent='“'+today.quote+'”';
const m=document.getElementById('dailyMission');if(m)m.textContent=today.mission;
const dash=document.getElementById('dashboard');
if(dash&&!document.getElementById('dailyChallenge')){const card=document.createElement('article');card.className='card daily-challenge';card.id='dailyChallenge';card.innerHTML='<span class="eyebrow">⚡ DAILY ELA CHALLENGE</span><h2>'+today.title+'</h2><p>Fresh challenge of the day. Come back tomorrow for a new one.</p><h3>'+today.question+'</h3>'+today.choices.map((x,n)=>'<button class="answer dailyChoice" data-i="'+n+'">'+x+'</button>').join('')+'<div class="feedback" id="dailyFeedback"></div>';const grid=dash.querySelector('.grid');if(grid)grid.prepend(card)}
document.addEventListener('click',e=>{const b=e.target.closest('.dailyChoice');if(!b)return;const ok=Number(b.dataset.i)===today.answer;b.parentElement.querySelectorAll('.dailyChoice').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');const f=document.getElementById('dailyFeedback');if(f)f.textContent=ok?'Great thinking! +10 XP.':'Good try—look back at the clues and think again.';if(ok){const v=Number(localStorage.getItem('dkxp')||120)+10;localStorage.setItem('dkxp',v);const x=document.getElementById('xp');if(x)x.textContent=v;const p=document.getElementById('parentXP');if(p)p.textContent=v}});