// Fresh, age-appropriate daily ELA rotation. Educational content uses fictional/neutral names only.
const DAILY_ROTATION=[
{type:'Reading',icon:'🦖',quote:'Every new clue is a footprint leading to a smarter idea.',mission:'Read for one detail that proves your answer.',title:'The Fossil Trail',passage:'A young fossil team noticed three different footprints near a muddy riverbank. Instead of guessing which dinosaur made them, the team measured each print and compared the shapes. One set had three long toes and a narrow heel. Their notes gave the scientists evidence to investigate further.',question:'Why did the team measure the footprints?',choices:['To collect evidence before making a conclusion.','To make the footprints disappear.','To prove every dinosaur had the same feet.'],answer:0},
{type:'Vocabulary',icon:'🔤',quote:'A strong reader turns unfamiliar words into new tools.',mission:'Use context to unlock one new word.',title:'Word Fossil',passage:'The trail became treacherous when loose rocks covered the steep path. The hikers slowed down and watched every step.',question:'What does treacherous most likely mean?',choices:['Dangerous or difficult','Bright and colorful','Short and simple'],answer:0},
{type:'Grammar',icon:'🏟️',quote:'Small grammar fixes can make your ideas score big.',mission:'Spot the sentence that needs a smart edit.',title:'Comma Kick',passage:'The team packed water, notebooks, snacks, and a camera before heading to the dinosaur dig.',question:'Which sentence correctly uses a comma after an introductory phrase?',choices:['Before the match, the players warmed up.','Before, the match the players warmed up.','Before the match the, players warmed up.'],answer:0},
{type:'Writing',icon:'✍️',quote:'Your ideas get stronger every time you practice putting them into words.',mission:'Write one vivid sentence today.',title:'Write the Winning Play',passage:'Imagine a dinosaur-themed soccer match during a sudden rainstorm. The team must solve a problem before the final whistle.',question:'Which detail would make the scene more vivid?',choices:['Rain drummed on the stadium roof as the players searched for dry ground.','It was a soccer game.','The players were there.'],answer:0},
{type:'Quiz',icon:'🏆',quote:'Great readers do not rush to the answer—they hunt for the evidence.',mission:'Choose the answer the text can prove.',title:'Evidence Cup',passage:'Kai missed the first two shots during practice. Instead of quitting, Kai asked the coach for one tip, practiced the footwork slowly, and tried again. By the end of practice, the shots were more accurate.',question:'Which theme is best supported?',choices:['Persistence and practice can improve a skill.','The first attempt is always perfect.','Asking for help means you cannot learn.'],answer:0},
{type:'Reading',icon:'📖',quote:'Curiosity is a superpower: one good question can open a whole new world.',mission:'Find the main idea before choosing a detail.',title:'The Museum Map',passage:'The museum placed dinosaur fossils in time-period order. Visitors could follow the path from older fossils to newer ones and see how scientists use evidence to understand changes in prehistoric life.',question:'What is the main idea?',choices:['The museum uses organized fossil displays to help visitors understand prehistoric life.','Every fossil in the museum is from the same dinosaur.','Visitors only visit museums to see maps.'],answer:0},
{type:'Vocabulary',icon:'🧩',quote:'Words are building blocks—add one new block to your toolkit today.',mission:'Find a word part and explain what it means.',title:'Prefix Power',passage:'The word reread contains the prefix re-, which often means “again.” A reader can reread a tricky paragraph to understand it better.',question:'What does reread mean?',choices:['Read again','Read before','Read without looking'],answer:0},
{type:'Grammar',icon:'⚽',quote:'Clear sentences help your teammates understand your best ideas.',mission:'Choose the sentence that is complete.',title:'Sentence Stadium',passage:'A complete sentence expresses a complete thought and normally has a subject and predicate.',question:'Which is a complete sentence?',choices:['After the final whistle.','The team celebrated after the final whistle.','Running toward the goal.'],answer:1},
{type:'Writing',icon:'📝',quote:'A good writer notices details other people might miss.',mission:'Add a sensory detail to your writing.',title:'Dinosaur Dialogue',passage:'Two young explorers discover a dinosaur footprint and disagree about what made it.',question:'Which opening uses dialogue to move the story forward?',choices:['“Look at those three toes!” Maya whispered. “I think we found something important.”','There was a footprint.','The explorers were explorers.'],answer:0},
{type:'Quiz',icon:'🥇',quote:'Mistakes are clues. Use them to make your next play smarter.',mission:'Use a clue from the passage before answering.',title:'Character Coach',passage:'At first, a player stayed quiet during team planning. After noticing that one suggestion helped the team score, the player began sharing ideas more often.',question:'How did the character change?',choices:['The character became more confident about sharing ideas.','The character stopped listening.','The character forgot how to play.'],answer:0},
{type:'Reading',icon:'🔎',quote:'Every paragraph has clues—be the detective who finds them.',mission:'Make an inference and name the clue.',title:'The Missing Cones',passage:'The practice cones were missing from the field. Wet footprints led from the equipment shed to the sideline, where the cones were stacked beside a raincoat.',question:'What can the reader infer?',choices:['Someone moved the cones after the rain began.','The cones vanished forever.','The team never used cones.'],answer:0},
{type:'Vocabulary',icon:'🌟',quote:'Precise words make ordinary ideas sparkle.',mission:'Swap a vague word for a more precise one.',title:'Word Choice Challenge',passage:'The runner moved quickly toward the open goal. A precise writer can replace “moved quickly” with a stronger verb.',question:'Which verb is most precise?',choices:['sprinted','went','did'],answer:0},
{type:'Grammar',icon:'📚',quote:'Strong writers edit because strong ideas deserve clear sentences.',mission:'Find the best way to join two ideas.',title:'Run-On Rescue',passage:'Two complete thoughts need correct punctuation or a conjunction when they are joined.',question:'Which sentence fixes the run-on “The ball rolled away I chased it.”?',choices:['The ball rolled away, so I chased it.','The ball rolled away I chased it.','The ball rolled away chased it.'],answer:0},
{type:'Writing',icon:'🎯',quote:'Your first draft is a starting point, not the finish line.',mission:'Revise one sentence to make it clearer.',title:'Championship Story',passage:'The final match is tied. A teammate notices an open path, but the team must decide whether to pass or shoot.',question:'Which writing move would build suspense?',choices:['Show the character noticing the choice and thinking about the consequences.','Tell the ending first and skip the decision.','Use the same sentence repeatedly.'],answer:0}
];
const dayNumber=Math.floor(Date.now()/86400000);const today=DAILY_ROTATION[dayNumber%DAILY_ROTATION.length];
const q=document.getElementById('dailyQuote');if(q)q.textContent='“'+today.quote+'”';
const m=document.getElementById('dailyMission');if(m)m.textContent=today.icon+' '+today.mission;
const dash=document.getElementById('dashboard');
if(dash&&!document.getElementById('dailyChallenge')){const card=document.createElement('article');card.className='card daily-challenge';card.id='dailyChallenge';card.innerHTML='<span class="eyebrow">⚡ DAILY '+today.type.toUpperCase()+' CHALLENGE</span><h2>'+today.icon+' '+today.title+'</h2>'+(today.passage?'<p class="daily-passage">'+today.passage+'</p>':'')+'<h3>'+today.question+'</h3>'+today.choices.map((x,n)=>'<button class="answer dailyChoice" data-i="'+n+'">'+x+'</button>').join('')+'<div class="feedback" id="dailyFeedback"></div>';const grid=dash.querySelector('.grid');if(grid)grid.prepend(card)}
const writingPrompts=['Write a short scene in which a dinosaur team uses teamwork to solve a soccer problem.','Describe a fossil discovery using at least three sensory details.','Write a paragraph explaining why practice can improve a skill.','Create a dialogue between two teammates who disagree and then find a solution.','Write a beginning for a story about a mysterious footprint near a soccer field.'];
const wp=writingPrompts[dayNumber%writingPrompts.length];const writingPage=document.getElementById('writing');if(writingPage){const prompt=writingPage.querySelector('.writing-grid .card p');if(prompt)prompt.textContent=wp;}
document.addEventListener('click',e=>{const b=e.target.closest('.dailyChoice');if(!b)return;const ok=Number(b.dataset.i)===today.answer;b.parentElement.querySelectorAll('.dailyChoice').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');const f=document.getElementById('dailyFeedback');if(f)f.textContent=ok?'Great thinking! +10 XP.':'Good try—use the passage clues and try the reasoning again.';if(ok){const v=Number(localStorage.getItem('dkxp')||120)+10;localStorage.setItem('dkxp',v);const x=document.getElementById('xp');if(x)x.textContent=v;const p=document.getElementById('parentXP');if(p)p.textContent=v}});